---
# role: ansible-role-timesyncd
# file: molecule/all/molecule.yml

dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/shared/yamllint.yml
platforms:
  - name: timesyncd-amazon
    image: "jam82/amazon-molecule:latest"
    command: "/usr/lib/systemd/systemd"
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: timesyncd-arch
    image: "jam82/arch-molecule:latest"
    command: "/usr/lib/systemd/systemd"
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: timesyncd-centos7
    image: "jam82/centos-molecule:7"
    command: "/usr/lib/systemd/systemd"
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: timesyncd-centos8
    image: "jam82/centos-molecule:8"
    command: "/usr/lib/systemd/systemd"
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: timesyncd-debian9
    image: "jam82/debian-molecule:9"
    command: "/lib/systemd/systemd"
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: timesyncd-debian10
    image: "jam82/debian-molecule:10"
    command: "/lib/systemd/systemd"
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: timesyncd-debian
    image: "jam82/debian-molecule:latest"
    command: "/lib/systemd/systemd"
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: timesyncd-suse15
    image: "jam82/suse-molecule:15"
    command: "/usr/lib/systemd/systemd"
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-suse
    image: "jam82/suse-molecule:latest"
    command: "/usr/lib/systemd/systemd"
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: timesyncd-suse-tumbleweed
    image: "jam82/suse-molecule:tumbleweed"
    command: "/usr/lib/systemd/systemd"
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: timesyncd-oracle7
    image: "jam82/oracle-molecule:7"
    command: "/usr/lib/systemd/systemd"
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: timesyncd-oracle8
    image: "jam82/oracle-molecule:8"
    command: "/usr/lib/systemd/systemd"
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: timesyncd-oracle
    image: "jam82/oracle-molecule:latest"
    command: "/usr/lib/systemd/systemd"
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: timesyncd-ubuntu1604
    image: "jam82/ubuntu-molecule:16.04"
    command: "/lib/systemd/systemd"
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: timesyncd-ubuntu1804
    image: "jam82/ubuntu-molecule:18.04"
    command: "/lib/systemd/systemd"
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: timesyncd-ubuntu
    image: "jam82/ubuntu-molecule:latest"
    command: "/lib/systemd/systemd"
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  log: True
  lint:
    name: ansible-lint
  playbooks:
    prepare: ../shared/prepare.yml
    converge: ../shared/playbook.yml
  inventory:
    group_vars:
      all:
        timesyncd_enabled: True
scenario:
  name: all
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore"
  directory: ../tests
  options:
    v: True
    sudo: True
  lint:
    name: flake8
