---
# role: ansible-role-systemd-timesyncd
# file: .travis.yml

language: python

python:
  - "3.9"

services: docker

branches:
  only:
    - main

cache:
  pip: true
  directories:
  - ".tox"

env:
  global:
    - TOX_PARALLEL_NO_SPINNER=1
  jobs:
    - TOX_IMG="Arch"      TOX_ANSIBLE="{29,210}"
    - TOX_IMG="Debian"    TOX_ANSIBLE="{29,210}"
    - TOX_IMG="OpenSuse"  TOX_ANSIBLE="{29,210}"
    - TOX_IMG="Ubuntu"    TOX_ANSIBLE="{29,210}"

before_install:
  - python -m pip install --upgrade pip

install:
  - pip install tox-travis

script:
  - tox -e $(echo py${TRAVIS_PYTHON_VERSION} | tr -d .)-an${TOX_ANSIBLE}-${TOX_IMG} -p
  - rm -r .tox/py*/log/*
  - find . -type f -name '*.py[co]' -delete -o -type d -name __pycache__ -delete
