---
# role: ansible-role-timesyncd
# file: tasks/main.yml

- name: Import tasks for role ansible-role-timesyncd
  import_tasks: tasks.yml
  when: timesyncd_enabled | bool
    and ansible_os_family == 'Archlinux'
    or (ansible_distribution == 'Debian' and ansible_distribution_major_version is version("9", ">="))
    or (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version is version("16", ">="))
