---
# role: ansible-role-timesyncd
# file: tasks/main.yml

- name: Import tasks for role ansible-role-timesyncd
  import_tasks: tasks.yml
  when: timesyncd_role_enabled | bool
    and ansible_service_mgr == 'systemd'
    and ansible_os_family == 'Archlinux'
    or (ansible_distribution == 'Debian' and ansible_distribution_major_version is version("9", ">="))
    or (ansible_distribution == 'Fedora' and ansible_distribution_major_version is version("29", ">="))
    or (ansible_distribution == 'openSUSE Leap' and ansible_distribution_major_version is version("15", ">="))
    or (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version is version("16", ">="))
