---
# role: ansible-role-systemd-timesyncd
# file: molecule/vbox/molecule.yml

dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
    type: virtualbox
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: systemd-timesyncd-alpine313
    box: "generic/alpine313"
    cpus: 2
    memory: 1024
  - name: systemd-timesyncd-amazonlinux2
    box: "bento/amazonlinux-2"
    cpus: 2
    memory: 1024
  - name: systemd-timesyncd-arch
    box: "archlinux/archlinux"
    cpus: 2
    memory: 1024
  - name: systemd-timesyncd-centos7
    box: "centos/7"
    cpus: 2
    memory: 1024
  - name: systemd-timesyncd-centos8
    box: "centos/8"
    cpus: 2
    memory: 1024
  - name: systemd-timesyncd-debian9
    box: "debian/stretch64"
    cpus: 2
    memory: 1024
  - name: systemd-timesyncd-debian10
    box: "debian/buster64"
    cpus: 2
    memory: 1024
  - name: systemd-timesyncd-debian11
    box: "debian/bullseye64"
    cpus: 2
    memory: 1024
  - name: systemd-timesyncd-fedora33
    box: "fedora/33-cloud-base"
    cpus: 2
    memory: 1024
  - name: systemd-timesyncd-suse-leap-15
    box: "bento/opensuse-leap-15"
    cpus: 2
    memory: 1024
  - name: systemd-timesyncd-oracle7
    box: "generic/oracle7"
    cpus: 2
    memory: 1024
  - name: systemd-timesyncd-oracle8
    box: "generic/oracle8"
    cpus: 2
    memory: 1024
  - name: systemd-timesyncd-ubuntu1804
    box: "ubuntu/bionic64"
    cpus: 2
    memory: 1024
  - name: systemd-timesyncd-ubuntu2004
    box: "ubuntu/focal64"
    cpus: 2
    memory: 1024
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
  inventory:
    group_vars:
      all:
        hosts_role_enabled: true
verifier:
  name: ansible
