---
# role: ansible-role-timesyncd
# file: molecule/shared/prepare.yml

- name: Prepare
  hosts: all
  gather_facts: True
  become: True
  tasks:
    - name: Update apt cache
      apt:
        name: tzdata
        state: present
        update_cache: yes
      when: ansible_pkg_mgr == 'apt'

    - name: Update pacman cache
      pacman:
        name: tzdata
        state: present
        update_cache: yes
      when: ansible_pkg_mgr == 'pacman'
