---
# role: ansible-role-timesyncd
# file: molecule/shared/prepare.yml

- name: Prepare
  hosts: all
  gather_facts: True
  become: True
  tasks:
    - name: Update apt cache
      apt:
        name: grep
        state: present
        update_cache: yes
      when: ansible_pkg_mgr == 'apt'

    - name: Update dnf cache
      dnf:
        name: grep
        state: present
        update_cache: yes
      when: ansible_pkg_mgr == 'dnf'

    - name: Update pacman cache
      pacman:
        name: grep
        state: present
        update_cache: yes
      when: ansible_pkg_mgr == 'pacman'

    - name: Update yum cache
      yum:
        name: grep
        state: present
        update_cache: yes
      when: ansible_pkg_mgr == 'yum'

    - name: Install EPEL
      yum:
        name: epel-release
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Update zypper cache
      zypper:
        name: grep
        state: present
        update_cache: yes
      when: ansible_pkg_mgr == 'zypper'
